
import React from 'react';
import { ArrowLeft, Shield, FileText, RefreshCw } from 'lucide-react';

interface PoliciesViewProps {
  onBack: () => void;
}

const PoliciesView: React.FC<PoliciesViewProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100 bg-white sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <button 
            onClick={onBack}
            className="flex items-center gap-2 text-gray-500 hover:text-gray-900 font-semibold transition-colors"
          >
            <ArrowLeft size={20} /> Back to Home
          </button>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center text-white font-bold">V</div>
            <span className="font-bold">Legal Hub</span>
          </div>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto px-6 py-16 space-y-16">
        <header className="text-center space-y-4">
          <h1 className="text-5xl font-extrabold text-gray-900 tracking-tight">Policies & Legal</h1>
          <p className="text-gray-500 text-lg">Transparency and safety are at the core of our platform.</p>
        </header>

        <section className="space-y-8">
          <div className="flex items-center gap-4 text-blue-600">
            <FileText size={32} />
            <h2 className="text-3xl font-bold">Terms of Service</h2>
          </div>
          <div className="prose prose-blue max-w-none text-gray-600 space-y-4">
            <p><strong>Last Updated: September 29, 2025</strong></p>
            <p>By using the Vekkam Engine ("Service"), you agree to be bound by these Terms.</p>
            <ol className="list-decimal pl-6 space-y-2">
              <li><strong>Acceptance of Terms:</strong> Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms.</li>
              <li><strong>User Conduct:</strong> You agree to use the Service only for lawful study purposes. Any misuse, including unauthorized scraping, bulk downloading, or attempt to reverse-engineer our models, is strictly prohibited.</li>
              <li><strong>Intellectual Property:</strong> All content generated by the Service from your uploaded materials remains your property. However, the models, interfaces, and technology of Vekkam are the exclusive property of the Company.</li>
              <li><strong>Disclaimer:</strong> We do not guarantee academic performance or score improvement. The Service is an assistive tool; results depend on individual effort and application.</li>
            </ol>
          </div>
        </section>

        <section className="space-y-8">
          <div className="flex items-center gap-4 text-emerald-600">
            <Shield size={32} />
            <h2 className="text-3xl font-bold">Privacy Policy</h2>
          </div>
          <div className="prose prose-emerald max-w-none text-gray-600 space-y-4">
            <p><strong>Last Updated: September 29, 2025</strong></p>
            <p>We prioritize your privacy above all else.</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Data Collection:</strong> We collect user authentication data (via Google OAuth or Email), payment information (handled securely by Razorpay), and your uploaded files.</li>
              <li><strong>Data Usage (The Core Promise):</strong> Your uploaded study materials and generated notes <strong>are never used to train or improve our foundational AI models.</strong> They are stored securely for your personal sessions only.</li>
              <li><strong>Security:</strong> We use industry-standard encryption for data transfer and storage. Payment processing is handled by Razorpay, an external, secure gateway.</li>
              <li><strong>Retention:</strong> You may delete your data at any time via session settings. We retain basic usage data for billing and feature analysis.</li>
            </ul>
          </div>
        </section>

        <section className="space-y-8 pb-20">
          <div className="flex items-center gap-4 text-amber-600">
            <RefreshCw size={32} />
            <h2 className="text-3xl font-bold">Return & Refund Policy</h2>
          </div>
          <div className="prose prose-amber max-w-none text-gray-600 space-y-4">
            <p><strong>Effective Date: September 29, 2025</strong></p>
            <p>Due to the immediate and intangible nature of digital service access, our policy is as follows:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Subscription Purchases:</strong> All sales for the monthly "Unlocked" subscription (₹100.00 INR) are <strong>final and non-refundable</strong> immediately upon successful payment through Razorpay.</li>
              <li><strong>Exceptions:</strong> Refunds will only be considered in cases of documented technical failure where the Service remains inaccessible for more than 48 consecutive hours after purchase.</li>
              <li><strong>Contact:</strong> For refund inquiries, please contact <strong>team.vekkam@gmail.com</strong> with your Order ID and reason.</li>
            </ul>
          </div>
        </section>
      </div>
    </div>
  );
};

export default PoliciesView;
